"""Every dataset that appears on screen comes from here — real or synthetic.

Real datasets are loaded from the curated copies in data/ (written by tools/fetch_data.py;
licences and citations in data/PROVENANCE.md). Synthetic datasets must be generated by a
function in this module with a fixed seed and a docstring stating the generating process,
so the narration can truthfully say "here is data drawn from ...". Never invent data inline
in a scene.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

DATA = Path(__file__).resolve().parents[2] / "data"
LB_TO_KG = 0.45359237


def auto_mpg() -> pd.DataFrame:
    """UCI Auto MPG (Quinlan 1993; CC BY 4.0; doi:10.24432/C5859H). 398 cars, 1970-82.

    Columns: mpg, cylinders, displacement (cu in), horsepower (6 missing -> NaN),
    weight_lb, weight_kg, acceleration (s), model_year (1970-82), origin (usa/europe/japan),
    name. weight_kg = weight_lb * 0.45359237 (exact definition of the pound).
    """
    cols = ["mpg", "cylinders", "displacement", "horsepower", "weight_lb", "acceleration",
            "model_year", "origin", "name"]
    df = pd.read_csv(DATA / "auto_mpg" / "auto-mpg.data", sep=r"\s+", names=cols,
                     na_values="?", quotechar='"')
    df["weight_kg"] = df["weight_lb"] * LB_TO_KG
    df["model_year"] = df["model_year"] + 1900
    df["origin"] = df["origin"].map({1: "usa", 2: "europe", 3: "japan"})
    return df


def fuel_economy() -> pd.DataFrame:
    """US DOE/EPA fuel economy data (fueleconomy.gov; US federal work, public domain).

    Curated subset: model years 2020+, conventional (non-hybrid, non-electric, non-FFV)
    gasoline vehicles. Key pair for regression: displ (engine litres) -> comb08 (combined
    mpg). The conditional spread of comb08 shrinks as displ grows, and the mean is curved
    (roughly ∝ 1/displ) — a natural lead-in to GLMs. Fetch date in data/fuel_economy/FETCHED.
    """
    return pd.read_csv(DATA / "fuel_economy" / "vehicles_2020plus_gasoline.csv")


def sample(df: pd.DataFrame, n: int, seed: int) -> pd.DataFrame:
    """Reproducible subsample for on-screen scatters (fewer points read better)."""
    return df.sample(n=min(n, len(df)), random_state=seed).sort_index()


def linear_gaussian(n: int = 60, seed: int = 7, beta0: float = 2.0, beta1: float = 0.5,
                    sigma: float = 0.6, x_range: tuple[float, float] = (0.0, 6.0)):
    """Synthetic: x ~ Uniform(x_range); y | x ~ Normal(beta0 + beta1 * x, sigma^2).

    Returns (x, y) numpy arrays. Used by gallery/ component demos.
    """
    rng = np.random.default_rng(seed)
    x = rng.uniform(*x_range, size=n)
    y = beta0 + beta1 * x + rng.normal(0.0, sigma, size=n)
    return x, y
